FROM {{ image_spec("base-tools") }}
MAINTAINER {{ maintainer }}

{{ copy_sources("seecloud/security", "/security") }}

RUN pip install -r /security/requirements.txt \
    && pip install --upgrade /security