#%RAML 1.0
title: Seecloud Security Service API
version: v0.1
mediaType: application/json
types:
  Issue:
    type: object
    properties:
      id: string
      type: string
      description: string
      region: string
      discovered_at: datetime
      confirmed_at: datetime
      tenant_id?: string
      user_id?: string
      data?: string
      resolved_at?: datetime
    example:
      id: "id2"
      type: "Type2"
      description: "Test issue Type2"
      region: "region1"
      discovered_at: "2016-12-15 16:18:22 +00"
      confirmed_at: "2016-12-15 16:18:22 +00"

/api/{version}/:
  /region/{region_name}/security/issues/{period}:
    description: List issues for given region and period
    get:
      responses:
        200:
          body:
            schema:
              type: object
              properties:
                issues:
                  type: array
                  items:
                    type: Issue
              required: issues
